export const INITIAL_TERMS = [
  ["day-neutral plant","What type of plant flowers regardless of the length of day or night (i.e. its flowering is not triggered by photoperiod — the relative duration of light and darkness)?"],
  ["deciduous","What term describes a tree or shrub that sheds ALL of its leaves at the end of each growing season?"],
  ["defoliant","What is a synthetic (man-made) chemical called when it causes a plant's leaves to drop prematurely?"],
  ["determinate growth","What term describes growth that stops once a plant or organ reaches a genetically predetermined (fixed by DNA) size?"],
  ["diageotropic","What term describes the horizontal growth of a plant part — i.e. growing at a right angle to the pull of gravity?"],
  ["diatom","What is a unicellular (single-celled) alga found in marine or freshwater environments, with a cell wall made of two interlocking silica halves?"],
  ["dicot","What subclass of flowering plants is characterised by having TWO cotyledons (seed leaves) in their seeds?"],
  ["differentiation","What process describes how unspecialised parenchyma cells undergo physical and physiological changes to become specialised cells?"],
  ["diffuse root system","What is another name for a fibrous root system (a highly branched, spreading network of roots with no single dominant root)?"],
  ["dioecious","What term describes a plant species where male and female reproductive organs are on entirely SEPARATE individual plants?"],
  ["diploid","What term describes a cell or organism that has TWO complete sets of chromosomes?"],
  ["disbudder","What is a synthetic chemical called when its purpose is to cause immature flower buds to be shed from the plant?"],
  ["disc flower","What type of small, tubular flower is found packed at the CENTRE of a composite flower head (e.g. a daisy or sunflower)?"],
  ["DNA (deoxyribonucleic acid)","What molecule carries the genetic information that makes up genes and determines inherited characteristics?"],
  ["dominant species","What term describes the most abundant and ecologically influential species in a plant community?"],
  ["dominant trait","What type of genetic trait is controlled by a gene that MASKS or overrides the expression of a comparable recessive gene?"],
  ["dormant / dormancy","What term describes a plant or seed in a state of reduced cellular activity — essentially paused growth, often during winter or drought?"],
  ["drip tip","What leaf feature — a long, pointed tip — helps channel rainwater off the leaf surface quickly?"],
  ["drip zone","What is the area of soil beneath a tree's leaf canopy called, where root tips are concentrated?"],
  ["egg","In plant reproduction, what is the female sex cell (gamete) called?"],
  ["embryo","What is the immature, undeveloped plant found inside a seed called?"],
  ["endodermis","What is the layer of specialised cells in a root called that sits between the cortex and the vascular tissues?"],
  ["endosperm","What is the nutrient-rich food-storage tissue inside a seed called?"],
  ["enzyme","What type of protein molecule speeds up (catalyses) biochemical reactions inside living cells without being used up itself?"],
  ["epidermal hair","What term describes a thin filament of cells that arises from the outer skin (epidermis) of a plant?"],
  ["epidermis","What is the outermost protective layer of cells covering the surface of a herbaceous plant organ?"],
  ["epigeous germination","What type of seed germination pushes the cotyledons (seed leaves) UP above the soil surface?"],
  ["epiphyll","What term describes an organism such as a fungus or moss that grows ON the surface of a living leaf?"],
  ["epiphyte","What is a plant called that grows ON another plant, using it purely for physical support?"],
  ["ethylene","What gaseous plant hormone is produced in large amounts by ripening fruits and damaged plant tissues?"],
  ["etiolation","What condition affects a plant grown in darkness, causing a pale, elongated stem and underdeveloped leaves?"],
  ["evergreen","What type of woody perennial plant retains and bears leaves ALL year round?"],
  ["fasciation","What abnormal growth condition produces flat, ribbon-like or fused stems and inflorescences?"],
  ["fermentation","What metabolic process partially breaks down sugar molecules in the ABSENCE of oxygen?"],
  ["fiber","What type of plant cell is very long, has thick walls, and dies at maturity — providing structural support?"],
  ["fibrous root system","What type of root system consists of many highly branched, roughly equal-sized roots with no single dominant root?"],
  ["field capacity","What is another term for water-holding capacity — the maximum water a soil holds after gravity drainage?"],
  ["filament","What is the slender stalk of a stamen that holds the anther in position?"],
  ["flower","What is the reproductive structure of an angiosperm, bearing the organs needed for sexual reproduction?"],
  ["food","In biology, what term describes an organic substance — especially carbohydrates, fats, and proteins — providing energy and body-building materials?"],
  ["fruit","In botany, what is a mature ovary called after fertilisation?"],
  ["gall","What is an abnormal swelling or growth on a plant called, typically caused by an invading organism?"],
  ["gamete","What term describes a sex cell — either a sperm or an egg — used in sexual reproduction?"],
  ["gametophyte","What is a haploid plant generation called when it produces gametes during the alternation of generations life cycle?"],
  ["gene","What is the basic unit of genetic inheritance — a specific segment of DNA encoding a particular characteristic?"],
  ["genotype","What term describes the complete genetic makeup of an organism?"],
  ["genus","What is the level of biological classification above species, grouping closely related plants?"],
  ["geotropism","What term describes the directional growth of a plant organ in response to gravity?"],
  ["germination","What process marks the beginning of active growth from a dormant seed, spore, or pollen grain?"],
  ["germination inhibitor","What is a chemical substance called when it prevents a seed from germinating?"],
  ["gibberellin","What class of plant hormones promotes internode elongation and cell enlargement?"],
  ["glaucous","What term describes a plant surface that appears smooth and coated with a powdery or waxy bloom?"],
  ["graft","What is the horticultural technique where a piece of one plant is joined to an established rooted plant so they grow as one?"],
  ["granum","What is the name for a stack of disc-like, pigment-containing membrane structures inside a chloroplast?"],
  ["gravitropism","What is another term for geotropism — the directional growth of a plant organ in response to gravity?"],
  ["growth retardant","What type of chemical substance is applied to plants to slow down or inhibit their growth?"],
  ["guard cell","What are the two specialised curved cells called that surround each stoma on a leaf, controlling its opening and closing?"],
  ["gum","What sticky, water-soluble plant secretion hardens on exposure to air to form a protective seal?"],
  ["guttation","What is the process called when water droplets are exuded from leaf margins, caused by root pressure rather than condensation?"],
  ["gymnosperm","What major group of plants produces seeds that are exposed, typically borne in cones?"],
  ["haploid","What term describes a cell that contains only ONE set of unpaired chromosomes?"],
  ["haustorium","What is the specialised penetrating organ of a parasitic plant called that absorbs water and nutrients from its host?"],
  ["heartwood","What is the central, dense, often darker-coloured region of a tree trunk's woody tissue called?"],
  ["hemiparasite","What type of parasite invades its host plant but only extracts water and mineral nutrients, still performing its own photosynthesis?"],
  ["herbaceous","What term describes a plant that is soft, green, and contains little or no woody tissue?"],
  ["herbicide","What is any chemical substance called when applied to plants to inhibit their growth or kill them?"],
  ["heterotrophic nutrition","What form of nutrition describes organisms that CANNOT make their own food and must obtain organic compounds externally?"],
  ["heterozygous","What genetic term describes an organism that has TWO DIFFERENT versions of a gene on its pair of homologous chromosomes?"],
  ["homologous chromosomes","What are the pairs of matching chromosomes called — one inherited from each parent — carrying genes for the same traits?"],
  ["homozygous","What genetic term describes an organism that has TWO IDENTICAL versions of a gene on its homologous chromosomes?"],
  ["hormone","What type of organic substance is produced by plants in very small amounts and transported to regulate growth and development?"],
  ["host","In parasitology, what is the plant or animal that a parasite lives on or in, obtaining its nourishment?"],
  ["humus","What is the dark, nutrient-rich organic matter in soil formed by decomposition of dead plant and animal material?"],
  ["hybrid","What is the offspring called when it results from crossing two plants of the same species that differ in one or more genes?"],
  ["hybrid vigor","What phenomenon describes the tendency of a hybrid to be larger, stronger, and more fertile than either parent?"],
  ["hypocotyl","What is the section of a seedling called that lies between the radicle and the point where cotyledons are attached?"],
  ["hypogeous germination","What type of seed germination keeps the cotyledons BELOW the soil surface while the shoot grows upward?"],
  ["imbibition","What is the physical process called when a dry seed absorbs water and swells — the first step in germination?"],
  ["incomplete flower","What is a flower called that is missing one or more of the four standard floral parts?"],
  ["indeterminate growth","What term describes growth that continues to an indefinite size throughout the plant's life?"],
  ["inflorescence","What is a specialised shoot called when it bears a cluster or arrangement of multiple flowers?"],
  ["insectivorous plant","What type of plant has adapted to capture and digest insects to supplement its nitrogen intake in poor soils?"],
  ["intercalary meristem","What is a meristem called when it is located BETWEEN regions of non-dividing tissue?"],
  ["internode","What is the section of stem called that lies BETWEEN two nodes?"],
  ["lateral bud","What is another name for an axillary bud — the bud found in the angle between a leaf and the stem?"],
  ["lateral meristem","What type of meristem runs along the LENGTH of a stem or root, enabling it to grow wider?"],
  ["latex","What is the thick, often milky fluid secretion produced by many plant species — sometimes acting as defence against herbivores?"],
  ["layering","What propagation method involves encouraging a still-attached shoot to grow new roots before being cut from the parent plant?"],
  ["leaf","What plant organ is an outgrowth of the stem, typically flat and green, serving as the primary site of photosynthesis?"],
  ["leaflet","What is each individual blade-like unit of a compound leaf called?"],
  ["leaf primordium","What is an immature, undeveloped leaf found at or near a growing stem tip called?"],
  ["leaf rosette","What arrangement of leaves radiates outward from a very short stem, forming a flat, circular cluster at ground level?"],
  ["leaf scar","What is the mark left on a stem called after a leaf has detached?"],
  ["leaf tendril","What is a modified leaf or part of a leaf that has become a thin, coiling structure used by climbing plants?"],
  ["lenticel","What is the small, raised pore found in the bark of woody stems called, allowing gas exchange?"],
  ["liana","What is a long-stemmed, woody climbing plant called that roots in the ground but uses trees for support?"],
  ["lignin","What tough, complex organic polymer is deposited into plant cell walls, giving them rigidity and strength?"],
  ["living stone","What group of succulent plants has evolved to mimic the appearance of small pebbles as camouflage?"],
  ["loam","What type of soil is a balanced mixture of sand, silt, and clay — considered ideal for most plants?"],
  ["long-day plant","What type of plant only flowers when the day length EXCEEDS its critical photoperiod?"],
  ["macronutrient","What term describes a mineral element that plants require in RELATIVELY LARGE quantities?"],
  ["megaspore","What is the larger spore type — the one that develops into the female gametophyte?"],
  ["meiosis","What type of cell division produces sex cells, halving the chromosome number?"],
  ["membrane","What thin, flexible biological structure composed of lipids and proteins surrounds and separates cell compartments?"],
  ["meristem","What is a zone in a plant called where cells are actively dividing and producing new cells for growth?"],
  ["mesophyll","What is the internal leaf tissue found between the upper and lower epidermis called, where most photosynthesis takes place?"],
  ["metabolism","What collective term describes ALL of the chemical reactions occurring within a living organism?"],
  ["microfibril","What is a tiny, thread-like strand of cellulose in a plant cell wall called?"],
  ["micronutrient","What term describes a mineral element that plants require in only very SMALL quantities but is still essential?"],
  ["microspore","What is the smaller spore type — the one that develops into the male gametophyte?"],
  ["middle lamella","What is the thin layer of pectin called that cements together the cell walls of two adjacent plant cells?"],
  ["mitochondria","What organelles are the site of cellular respiration — the process that releases energy from sugars?"],
  ["mitosis","What type of cell division produces two genetically identical daughter cells — used for growth and repair?"],
  ["molecule","What is the smallest unit of a chemical compound, consisting of two or more atoms bonded together?"],
  ["monocot","What subclass of flowering plants is characterised by having only ONE cotyledon in their seeds?"],
  ["monoecious","What term describes a plant that bears BOTH male and female flowers on the SAME individual plant?"],
  ["multiple fruit","What type of fruit forms when the ovaries of SEVERAL flowers on a single stem fuse together?"],
  ["mutation","What is an inheritable change in the DNA sequence of a gene called?"],
  ["mycorrhiza","What is the mutually beneficial association called between a fungus and the roots of a plant?"],
  ["nastic movement","What type of plant movement occurs in response to a general stimulus but is NOT directional?"],
  ["natural selection","What evolutionary process describes how individuals better adapted to their environment are more likely to survive and reproduce?"],
  ["necrosis","What is the localised death of plant cells or tissue called?"],
  ["nectar","What sweet, sugary liquid is secreted by special glands in flowers to attract pollinators?"],
  ["nectar guide","What are the contrasting colour markings on a flower's petals called that direct pollinators toward the nectar?"],
  ["nectary","What is the specialised gland within a flower that secretes nectar called?"],
  ["nitrogen cycle","What is the natural process called that describes the continuous movement of nitrogen between the atmosphere, soil, and organisms?"],
  ["nitrogen-fixation","What process converts atmospheric nitrogen gas into ammonia or nitrates that plants can absorb?"],
  ["node","What is the specific point on a stem called where leaves and axillary buds are attached?"],
  ["N-P-K ratio","What do the three numbers on a fertiliser label represent — the relative proportions of nitrogen, phosphorus, and potassium?"],
  ["nucleus","What is the membrane-bound organelle called that acts as the cell's control centre, housing the DNA?"],
  ["organ","In plant biology, what term describes a distinct structural part composed of multiple tissue types working together as a functional unit?"],
  ["organelle","What is a specialised structure within a cell called that carries out a specific function?"],
  ["organic","In chemistry, what term describes a compound that contains both carbon and hydrogen atoms bonded together?"],
  ["organism","What is any individual living entity capable of growth, reproduction, and response to stimuli?"],
  ["osmosis","What is the passive movement of water molecules across a selectively permeable membrane called?"],
  ["ovary","What is the enlarged, hollow base of a flower's pistil called that contains ovules and develops into a fruit?"],
  ["ovule","What is an immature, unfertilised seed called — the structure that after fertilisation develops into a mature seed?"],
  ["palisade cell","What type of elongated, chloroplast-rich cell is found in a tightly packed layer just beneath the upper epidermis of a leaf?"],
  ["palmate venation","What leaf vein pattern has major veins radiating outward from a SINGLE central point — like fingers of an outstretched hand?"],
  ["palmately compound leaf","What type of compound leaf has all its leaflets radiating outward from a single central point?"],
  ["panicle","What type of inflorescence is highly branched, with each branch bearing further branches and flowers?"],
  ["parallel venation","What leaf vein pattern has major veins running alongside each other from base to tip — typical of monocots?"],
  ["parasite","What is an organism called that obtains its nutrients by living on or in another living organism?"],
  ["parenchyma","What is the most common type of plant cell — thin-walled, loosely packed, and relatively unspecialised?"],
  ["parthenocarpy","What is the development of a fruit called when it occurs WITHOUT pollination or fertilisation — producing seedless fruits?"],
  ["pectin","What is the complex polysaccharide in plant cell walls that acts as a glue cementing neighbouring cells together?"],
  ["pedicel","What is the short individual stalk called that connects a single flower to the main stem of an inflorescence?"],
  ["perennial","What type of plant lives and grows for MORE than two years, flowering repeatedly over many growing seasons?"],
  ["perianth","What collective term describes ALL the non-reproductive floral parts — all the sepals and petals together?"],
  ["pericarp","What is the wall of a mature fruit called — the structure that develops from the ovary wall after fertilisation?"],
  ["pericycle","What is the layer of cells found just inside the endodermis in a root called — responsible for producing lateral roots?"],
  ["petal","What are the often brightly coloured, flattened floral parts called that surround the reproductive organs?"],
  ["petiolate leaf","What type of leaf has its blade connected to the stem by a distinct stalk?"],
  ["petiole","What is the stalk of a leaf called — the narrow structure connecting the leaf blade to the stem?"],
  ["pH","What scale (0-14) measures the relative acidity or alkalinity of a substance such as soil or water?"],
  ["phenotype","What term describes the observable physical characteristics of an organism?"],
  ["phloem","What vascular tissue transports dissolved sugars and organic nutrients from leaves to the rest of the plant?"],
  ["photoinduce","What term describes the triggering of a physiological process in a plant as a direct result of exposure to a specific photoperiod?"],
  ["photoperiodism","What is the biological response of plants to the RELATIVE lengths of day and night in a 24-hour cycle?"],
  ["photosynthesis","What is the process in which plants use light energy to convert carbon dioxide and water into glucose and oxygen?"],
  ["phototropism","What is the directional growth response of a plant organ called when it bends toward or away from a source of light?"],
  ["phytoalexin","What is a chemical compound called when a plant produces it to inhibit the growth of pathogens?"],
  ["phytotoxin","What is a plant-produced chemical called when it has toxic effects on herbivores and other invasive organisms?"],
  ["pilose","What term describes a plant surface covered with long, soft, relatively sparse hairs?"],
  ["pinnately compound leaf","What type of compound leaf has its leaflets arranged in two rows along BOTH sides of a central stalk?"],
  ["pinnate venation","What leaf vein pattern has one central midrib with secondary veins branching off on both sides?"],
  ["pistil","What is the FEMALE reproductive organ of a flower called — consisting of a stigma, style, and ovary?"],
  ["pit","What is a thin area or small opening in a plant cell wall called — allowing communication between neighbouring cells?"],
  ["pith","What is the spongy region of parenchyma cells found at the very CENTRE of a young stem?"],
  ["plagiotropic","What term describes the growth of a branch or root at an OBLIQUE ANGLE?"],
  ["plant growth regulator","What is another term for a plant hormone — a naturally occurring compound that controls growth at very low concentrations?"],
  ["plasmodesmata","What are the tiny channels called that pass through cell walls of adjacent plant cells, allowing molecules to move between them?"],
  ["plasmolysis","What is the process called when a plant cell loses so much water by osmosis that its cytoplasm shrinks away from the cell wall?"],
  ["pollen","What is the powdery structure called that develops from a microspore, serving as the male gametophyte?"],
  ["pollen tube","What is the thin tube called that grows from a germinating pollen grain and carries sperm cells to the female gametophyte?"],
  ["pollination","What is the process called when pollen is transferred from the anther to the stigma?"],
  ["polyploid","What term describes an organism whose cells contain THREE or MORE complete sets of chromosomes?"],
  ["prickle","What is a hard, sharp-pointed outgrowth of the epidermis of a stem or leaf called — as seen in roses?"],
  ["primary growth","What type of plant growth increases the LENGTH of stems and roots, arising from apical meristems?"],
  ["primary phloem","What is the food-conducting tissue called when first formed from the activities of apical meristems?"],
  ["primary tissue","What term describes any plant tissue formed during primary growth — produced by apical meristems?"],
  ["primary wall","What is the FIRST, flexible layer of cellulose deposited around a newly formed plant cell?"],
  ["primary xylem","What is the water-conducting tissue called when first formed from the activities of apical meristems?"],
  ["prop root","What is an adventitious root called when it grows downward from an above-ground stem to provide mechanical support?"],
  ["protoplasm","What term refers to ALL the living contents of a cell — including both the cytoplasm and the nucleus?"],
  ["pubescent","What term describes a plant surface covered with short, fine, soft hairs?"],
  ["raceme","What type of inflorescence has flowers attached by short stalks at intervals along an unbranched, elongated main stem?"],
  ["radicle","What is the embryonic root of a seedling called — the first structure to emerge from a germinating seed?"],
  ["raphide","What are the microscopic, needle-shaped crystals of calcium oxalate in plant cells called — which deter herbivores?"],
  ["ray flower","In a composite flower head, what are the outer, strap-shaped flowers called that form a ring around the disc flowers?"],
  ["receptacle","What is the enlarged tip of a flower stalk called to which all the flower parts are attached?"],
  ["recessive trait","What type of genetic trait is ONLY expressed when an organism has inherited two copies of the recessive gene?"],
  ["resin","What is the viscous, water-insoluble secretion produced by many conifers called — which hardens on exposure to air?"],
  ["resin canal","What is the tube-like channel in conifer wood called that secretes and transports resin?"],
  ["respiration","What is another term for cellular respiration — the process in which cells break down glucose to release energy?"],
  ["reticulate venation","What leaf vein pattern has veins that branch and interconnect to form a complex net-like network?"],
  ["rhizome","What is a horizontal, underground stem called that can produce new shoots and roots?"],
  ["ribosome","What are the tiny cellular organelles called that serve as the site where proteins are assembled from amino acids?"],
  ["ripeness-to-flower","What term describes the minimum size or maturity a plant must reach before it can respond to flowering signals?"],
  ["root","What is the typically underground organ of a plant that anchors it in the soil and absorbs water and minerals?"],
  ["root cap","What is the thimble-shaped mass of protective cells at the very tip of a growing root called?"],
  ["root hair","What is the thin, tubular extension of a root epidermal cell called that increases the surface area for absorbing water?"],
  ["root nodule","What is the small, rounded swelling on the roots of legumes called, which contains nitrogen-fixing bacteria?"],
  ["root pressure","What is the upward force called that develops in roots when active absorption of water pushes water up the xylem?"],
  ["root tuber","What is an enlarged, swollen root called that stores food and can produce adventitious shoots?"],
  ["runner","What is a horizontal stem called that grows along the soil surface and can produce new roots and shoots?"],
  ["sand","What is the coarsest inorganic soil component called — with particles from 0.02 to 2 mm — giving good drainage?"],
  ["saprophyte","What is an organism called that feeds on and breaks down DEAD organic matter?"],
  ["sapwood","What is the outer, lighter-coloured region of wood in a tree trunk called — still actively conducting water?"],
  ["scarify","What is the technique called when a seed coat is deliberately scratched or abraded to allow water to penetrate?"],
  ["scion","What is the piece of stem or bud from one plant called when inserted into the rootstock of another during grafting?"],
  ["sclereid","What is another name for a stone cell — a thick-walled, hardened cell providing hardness to structures like nut shells?"],
  ["secondary growth","What type of plant growth increases the GIRTH of stems and roots, produced by lateral meristems?"],
  ["secondary phloem","What is the food-conducting tissue called when produced by the vascular cambium during secondary growth?"],
  ["secondary product","What term describes a plant biochemical NOT directly involved in core metabolic processes — e.g. tannins or resins?"],
  ["secondary wall","What is the additional, often thicker layer of cell wall material called — providing extra strength, especially in wood cells?"],
  ["secondary xylem","What is the water-conducting tissue called when produced by the vascular cambium — essentially what we call wood?"],
  ["seed","What is the mature reproductive structure formed from a fertilised ovule — containing a dormant embryo and stored food?"],
  ["seed coat","What is the tough, protective outer covering of a seed called?"],
  ["seed germination","What is another term for germination — the process by which a dormant seed begins active growth?"],
  ["seed leaf","What is another name for a cotyledon — the first leaf present in a seed embryo?"],
  ["seedling","What is a very young plant called shortly after the seed has germinated?"],
  ["seismonastic motion","What type of plant movement is triggered by mechanical disturbance such as touch or vibration?"],
  ["self-pollination","What is it called when a flower's pollen is transferred to the stigma of the SAME flower or plant?"],
  ["senescence","What is the natural aging process in plants called — leading to progressive breakdown of cell structure?"],
  ["sepal","What are the outermost, typically leaf-like floral parts called that enclose and protect the flower bud before it opens?"],
  ["sessile leaf","What type of leaf has its blade attached DIRECTLY to the stem — without any petiole connecting them?"],
  ["shade-tolerant","What term describes a plant's ability to survive and grow effectively at LOW light intensities?"],
  ["shoot","What is the above-ground portion of a plant called that consists of a stem bearing leaves?"],
  ["short-day plant","What type of plant only flowers when the day length is SHORTER than its critical photoperiod?"],
  ["shrub","What is a woody, perennial plant called that has multiple stems branching from near the base?"],
  ["sieve plate","What is the perforated end wall of a sieve tube member called, through which nutrients flow between connected cells?"],
  ["sieve tube","What is the specialised, living cell in the phloem called that transports dissolved sugars?"],
  ["silt","What is the medium-sized inorganic soil particle called — with particles from 0.002 to 0.02 mm?"],
  ["simple fruit","What is a fruit called when it develops from the ovary of just ONE single flower?"],
  ["simple leaf","What type of leaf has a single, undivided blade?"],
  ["sorus","What is the cluster of spore-producing structures on the underside of a fern frond called?"],
  ["spadix","What is the spike-shaped inflorescence called that has small flowers in a fleshy central axis, typically surrounded by a spathe?"],
  ["spathe","What is the large, often brightly coloured, leaf-like bract called that wraps around or encloses a spadix?"],
  ["species","What is the fundamental unit of biological classification — a group of individuals that share many characteristics and can naturally interbreed?"],
  ["specific epithet","What is the second word of a species' binomial scientific name called?"],
  ["sperm","In plant reproduction, what is the male sex cell (gamete) called?"],
  ["spike","What type of inflorescence has flowers attached DIRECTLY to the main stem without individual stalks?"],
  ["spine","What is a hard, sharply pointed structure called when it is a MODIFIED LEAF — as in cacti?"],
  ["spongy cell","What type of loosely arranged photosynthetic cell is found in the lower layer of a leaf's mesophyll?"],
  ["spore","What is a single reproductive cell capable of growing DIRECTLY into a new plant without fertilisation?"],
  ["sporophyte","What is the diploid plant generation called that produces spores?"],
  ["springwood","What is xylem called when produced by the vascular cambium during SPRING — forming the pale part of an annual ring?"],
  ["spur","What is the hollow, tubular extension projecting from a flower's petal or sepal called — often containing nectar?"],
  ["stamen","What is the MALE reproductive organ of a flower called — consisting of a filament topped by the anther?"],
  ["starch","What is the main carbohydrate used for long-term food storage in plants — a polysaccharide of many linked glucose units?"],
  ["stem","What is the main above-ground axis of a plant called — the structure that bears leaves, buds, and flowers?"],
  ["stem tuber","What is the swollen, food-storing tip of an underground rhizome called — capable of producing new shoots?"],
  ["stigma","What is the sticky or feathery surface at the tip of a pistil called — the part that receives and traps pollen?"],
  ["stilt root","What is another term for a prop root — an adventitious root that grows from the stem above ground?"],
  ["stinging hair","What is a specialised, multicellular hair called that contains and injects an irritating fluid when touched?"],
  ["stipule","What are the small, leaf-like outgrowths found at the BASE of a leaf stalk in some plants called?"],
  ["stock","In grafting, what is the rooted plant called — into which the scion is inserted?"],
  ["stolon","What is another name for a runner — a horizontal stem that grows along or just below the soil surface?"],
  ["stoma (pl. stomata)","What is each tiny pore in the epidermis of a leaf called — surrounded by two guard cells that regulate gas exchange?"],
  ["stone cell","What is a type of sclerenchyma cell called when it has very thick, heavily lignified walls — giving gritty texture to pears?"],
  ["stratification","What pre-treatment for seeds involves exposing them to cold and moist conditions to break dormancy?"],
  ["style","What is the slender, column-like part of the pistil called that connects the stigma to the ovary?"],
  ["suberin","What is the waxy, water-repellent fatty substance called that is deposited into the walls of cork cells?"],
  ["sucker","What is a shoot that arises from an adventitious bud on a ROOT — growing upward through the soil?"],
  ["summerwood","What is xylem called when produced by the vascular cambium in LATE SUMMER — forming the darker part of an annual ring?"],
  ["symbiosis","What term describes a close, long-term biological interaction between two or more different species that benefits both?"],
  ["tannin","What class of bitter, astringent compounds in bark and leaves deters herbivores and pathogens?"],
  ["tap root","What type of root system has one main, prominent central root growing straight downward — often swollen to store food?"],
  ["tendril","What is a thin, coiling modified stem or leaf called that a climbing plant uses to grip supports?"],
  ["tepal","What is a floral part called when a flower's petals and sepals are indistinguishable — referred to collectively by this single term?"],
  ["terminal bud","What is another term for the apical bud — the bud at the TIP of a shoot containing the apical meristem?"],
  ["terminal bud scale scar","What is the ring-like scar left on a woody stem called, formed where the protective scales of the terminal bud were attached?"],
  ["thigmotropism","What directional growth response is triggered by PHYSICAL CONTACT or touch?"],
  ["thorn","What is a hard, sharply pointed structure called when it is a MODIFIED STEM — vascularised and difficult to break off cleanly?"],
  ["tissue","What term describes a group of cells of the same type all performing a common function?"],
  ["trace element","What is another term for micronutrient — a mineral element required by plants in very small amounts?"],
  ["tracheid","What type of elongated, dead water-conducting cell is found in gymnosperms and lower vascular plants?"],
  ["transpiration","What is the process called by which water is lost from a plant as water vapour — primarily through the open stomata of leaves?"],
  ["transpirational pull","What is the main driving force for water movement up through a plant — the tension created in the xylem when water evaporates from leaves?"],
  ["tree","What is a large, woody, perennial plant called that has a single, clearly defined main trunk?"],
  ["tropism","What is the directional growth movement of a plant organ called when caused by an external stimulus?"],
  ["tuber","What is a swollen, underground plant organ used for food storage — either a root tuber or a stem tuber?"],
  ["tuberous root","What is another term for a root tuber — an enlarged, swollen storage root?"],
  ["turgid","What term describes a plant cell that is swollen and firm because it is fully inflated with water?"],
  ["turgor pressure","What is the internal pressure called that builds up inside a plant cell as water enters by osmosis?"],
  ["twiner","What type of climbing plant stem grows by wrapping itself in a SPIRAL around a supporting structure?"],
  ["umbel","What type of inflorescence has all individual flower stalks arising from the SAME single point at the top of the stem?"],
  ["vacuole","What is the large, membrane-bound fluid-filled sac found in plant cells called?"],
  ["variegation / variegated","What term describes the inherited, irregular patterning of two or more colours in a leaf or petal?"],
  ["vascular bundle","What is a discrete strand of conducting tissue called — containing both xylem and phloem?"],
  ["vascular cambium","What is the narrow cylinder of meristematic cells called that produces secondary xylem and phloem?"],
  ["vascular plant","What major division of the plant kingdom includes any plant that has a specialised system of xylem and phloem tissues?"],
  ["vascular ray","What is a ribbon-like sheet of parenchyma cells called that runs radially across the secondary xylem and phloem?"],
  ["vascular tissue","What collective term describes the specialised cells and tissues — xylem and phloem — responsible for conducting water and food?"],
  ["vein","What is the strand of vascular tissue running through a leaf blade called, forming the visible network that supports the leaf?"],
  ["velamen","What is the specialised, spongy tissue on the OUTSIDE of aerial roots of orchids called?"],
  ["vernalization","What is the process called when a plant requires exposure to cold temperatures before it is able to flower?"],
  ["vessel","What is the wide, dead water-conducting cell in the xylem of angiosperms called — stacked to form long tubes?"],
  ["viable","What term describes a seed that is alive and capable of germinating under the right conditions?"],
  ["vivipary","What unusual phenomenon is it called when seeds germinate WHILE STILL ATTACHED to and inside the parent plant?"],
  ["water-holding capacity","What is the term for the MAXIMUM amount of water a soil can retain after excess water has drained away under gravity?"],
  ["whorled","What arrangement of leaves or plant parts is described when three or more arise from the SAME NODE on a stem?"],
  ["wood","What is the hard, dense tissue found in the stems and roots of trees called — composed mainly of secondary xylem?"],
  ["xanthophyll","What is a yellow or pale yellow accessory photosynthetic pigment called — found alongside chlorophyll in chloroplasts?"],
  ["xylem","What vascular tissue transports water and dissolved minerals from the roots upward through the plant?"],
  ["zygomorphic flower","What type of flower has an IRREGULAR shape — divisible into two mirror-image halves along only ONE plane?"],
  ["zygote","What is the single cell formed when a sperm and an egg fuse during fertilisation?"],
]
